<div {{ $attributes->merge(['class' => 'flex h-16 overflow-hidden']) }}>
    <ul class="flex animate-scroll px-3 my-auto gap-6">
        <li>
            <x-svgs.html/>
        </li>
        <li>
            <x-svgs.css/>
        </li>
        <li>
            <x-svgs.javascript/>
        </li>
        <li>
            <x-svgs.php/>
        </li>
        <li>
            <x-svgs.laravel/>
        </li>
        <li>
            <x-svgs.tailwind/>
        </li>
        <li>
            <x-svgs.alpine/>
        </li>
        <li>
            <x-svgs.livewire/>
        </li>
    </ul>
    <ul class="flex animate-scroll px-3 my-auto gap-6" aria-hidden="true">
        <li>
            <x-svgs.html/>
        </li>
        <li>
            <x-svgs.css/>
        </li>
        <li>
            <x-svgs.javascript/>
        </li>
        <li>
            <x-svgs.php/>
        </li>
        <li>
            <x-svgs.laravel/>
        </li>
        <li>
            <x-svgs.tailwind/>
        </li>
        <li>
            <x-svgs.alpine/>
        </li>
        <li>
            <x-svgs.livewire/>
        </li>
    </ul>
</div>